<?php //namespace Models;
include_once 'Conexion.php';
	
	class Formulario{
        private $idformulario;
        private $idlocal;
        private $for_fecha;
        private $for_horacom;
        private $for_horafin;
        private $idusuario;

		public function __construct(){
			
		}

		public function set($atributo, $contenido){
			$this->$atributo = $contenido;
		}

		public function get($atributo){
			return $this->$atributo;
		}

		public function agregarFormulario(){
                            
            $con = new Conexion();
			$sql = "INSERT INTO formulario(idlocal, for_fecha, for_horacom, for_horafin, idusuario) VALUES ({$this->idlocal}, '{$this->for_fecha}', '{$this->for_horacom}', '{$this->for_horafin}', {$this->idusuario})";
            $sql1 = "SELECT LAST_INSERT_ID() as idformulario";
            $con->consultaSimple($sql);
            $datos = $con->consultaRetorno($sql1);
            return $datos;
        }
        
        public function updateFormulario(){                            
            $con = new Conexion();
			$sql = "UPDATE formulario SET idlocal = {$this->idlocal}, for_fecha = '{$this->for_fecha}', for_horacom = '{$this->for_horacom}', for_horafin = '{$this->for_horafin}', idusuario = '{$this->idusuario}' WHERE idformulario = {$this->idformulario}";
            $con->consultaSimple($sql);
        }
        
        public function eliminarFormulario(){                            
            $con = new Conexion();
			$sql = "DELETE FROM formulario WHERE idformulario = {$this->idformulario}";
		    $sql1 = "DELETE FROM form_item_resp WHERE idformulario = {$this->idformulario}";
			$sql2 = "DELETE FROM form_cat WHERE idformulario = {$this->idformulario}";
            $con->consultaSimple($sql);
            $con->consultaSimple($sql1);
            $con->consultaSimple($sql2);
        }

        public function verFormulariosAuditor(){                            
            $con = new Conexion();
            $local = $_SESSION['localactual'];
			$sql = "SELECT formulario.idformulario, `local`.loc_nombre, formulario.for_horacom, respuesta.idrespuesta, respuesta.resp_nombre, count(form_item_resp.idrespuesta) as items FROM formulario, `local`, form_item_resp, respuesta WHERE formulario.idformulario = form_item_resp.idformulario AND formulario.idlocal = `local`.idlocal AND form_item_resp.idrespuesta = respuesta.idrespuesta AND formulario.for_fecha = '{$this->for_fecha}' AND `local`.idlocal = $local GROUP BY respuesta.resp_nombre, formulario.idformulario ORDER BY formulario.idformulario, respuesta.idrespuesta";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }
        
        public function verFormulariosSupervisor(){                            
            $con = new Conexion();
			$sql = "SELECT formulario.idformulario, `local`.loc_nombre, formulario.for_horacom, respuesta.idrespuesta, respuesta.resp_nombre, count(form_item_resp.idrespuesta) as items FROM formulario, `local`, form_item_resp, respuesta WHERE formulario.idformulario = form_item_resp.idformulario AND formulario.idlocal = `local`.idlocal AND form_item_resp.idrespuesta = respuesta.idrespuesta AND formulario.for_fecha = '{$this->for_fecha}' GROUP BY respuesta.resp_nombre, formulario.idformulario ORDER BY formulario.idformulario, respuesta.idrespuesta";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }

        public function informeFormulario(){                            
            $con = new Conexion();
			$sql = "SELECT categoria.idcategoria, categoria.cat_nombre, form_item_resp.idrespuesta, respuesta.resp_nombre, count(form_item_resp.idrespuesta)as aud 
            FROM formulario
            INNER JOIN form_item_resp ON formulario.idformulario = form_item_resp.idformulario 
            RIGHT JOIN respuesta ON form_item_resp.idrespuesta = respuesta.resp_valoracion 
            INNER JOIN item ON form_item_resp.iditem = item.iditem 
            INNER JOIN categoria ON item.idcategoria = categoria.idcategoria 
            
            WHERE formulario.idformulario = {$this->idformulario} GROUP BY resp_nombre, cat_nombre ORDER BY categoria.idcategoria, respuesta.resp_valoracion";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }

        public function evaluacionFormulario(){                            
            $con = new Conexion();
			$sql = "SELECT `local`.loc_nombre, item.idcategoria, categoria.cat_nombre, categoria.cat_peso, form_item_resp.iditem, item.it_nombre, item.it_descripcion, form_item_resp.idrespuesta, respuesta.resp_valoracion, respuesta.resp_nombre, form_item_resp.idformulario, formulario.for_fecha, formulario.for_horacom, formulario.for_horafin, formulario.idlocal,  formulario.idusuario, 
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idrespuesta = 3 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idformulario = {$this->idformulario}),2))*100 AS pbien,  
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idrespuesta = 2 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idformulario = {$this->idformulario}),2))*100 AS pintermedio, 
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idrespuesta = 1 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE idformulario = {$this->idformulario}),2))*100 AS pmal, 
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 1 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND idformulario = {$this->idformulario}),2))*100 AS pbien_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 1 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 1 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND idformulario = {$this->idformulario}),2))*100 AS pmal_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 2 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND idformulario = {$this->idformulario}),2))*100 AS pbien_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 2 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 2 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND idformulario = {$this->idformulario}),2))*100 AS pmal_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 3 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND idformulario = {$this->idformulario}),2))*100 AS pbien_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 3 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 3 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND idformulario = {$this->idformulario}),2))*100 AS pmal_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 4 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND idformulario = {$this->idformulario}),2))*100 AS pbien_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 4 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 4 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND idformulario = {$this->idformulario}),2))*100 AS pmal_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 5 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND idformulario = {$this->idformulario}),2))*100 AS pbien_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 5 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 5 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND idformulario = {$this->idformulario}),2))*100 AS pmal_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 6 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND idformulario = {$this->idformulario}),2))*100 AS pbien_prodinsumos,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 6 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND idformulario = {$this->idformulario}),2))*100 AS pintermedio_prodinsumos,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 6 AND idformulario = {$this->idformulario})/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND idformulario = {$this->idformulario}),2))*100 AS pmal_prodinsumos,
            (SELECT COUNT(item.iditem) FROM item) AS total,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 1 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_asplocal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 2 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_deposito,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 3 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_personal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 4 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_conequipamiento,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 5 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_vajilla,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp RIGHT JOIN item ON form_item_resp.iditem = item.iditem WHERE item.idcategoria = 6 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS total_prodinsumos,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp WHERE form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_asplocal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_deposito,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_personal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_conequipamiento,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_vajilla,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = {$this->idformulario}) AS evaluados_prodinsumos,
             ((ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 1)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 1))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 1),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 2)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 2))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 2),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 3)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 3))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 3),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 4)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 4))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 4),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 5)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 5))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 4),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND idformulario = {$this->idformulario} AND categoria.idcategoria = 6)/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item WHERE form_item_resp.iditem = item.iditem AND idformulario = {$this->idformulario} AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 6))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 6),2),0))) AS promedio_parcial,
            (SELECT ROUND((SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 1)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 2)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 3)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 4)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 5)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 6),2)) AS suma_pesos
                        FROM formulario
                        INNER JOIN form_item_resp ON formulario.idformulario = form_item_resp.idformulario 
                        RIGHT JOIN respuesta ON form_item_resp.idrespuesta = respuesta.resp_valoracion 
                        INNER JOIN item ON form_item_resp.iditem = item.iditem 
                        INNER JOIN categoria ON item.idcategoria = categoria.idcategoria 
                        INNER JOIN `local` ON formulario.idlocal = `local`.idlocal
                        
                        WHERE formulario.idformulario = {$this->idformulario} GROUP BY cat_nombre ORDER BY categoria.idcategoria, respuesta.resp_valoracion";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }
        
        public function verMultimedia(){                            
            $con = new Conexion();
			$sql = "SELECT form_cat.idcategoria, categoria.cat_nombre, form_cat.for_archivo, form_cat.for_observacion, form_cat.idformulario FROM formulario, form_cat, categoria WHERE form_cat.idformulario = formulario.idformulario AND form_cat.idcategoria = categoria.idcategoria AND formulario.idformulario = {$this->idformulario} ORDER BY categoria.idcategoria";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }
        
        public function formularioPorFecha(){                            
            $con = new Conexion();
			$sql = "SELECT `local`.loc_nombre, formulario.for_horacom, formulario.for_horafin FROM `local`, formulario WHERE formulario.idlocal = `local`.idlocal AND formulario.for_fecha = '{$this->for_fecha}'";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }
        
        public function verRespuestaItem(){                            
            $con = new Conexion();
			$sql = "SELECT categoria.idcategoria, categoria.cat_nombre, item.iditem, item.it_nombre, item.it_descripcion, respuesta.resp_nombre FROM categoria, item, form_item_resp, respuesta WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND form_item_resp.idrespuesta = respuesta.idrespuesta AND form_item_resp.idformulario = {$this->idformulario} ORDER BY categoria.idcategoria, item.iditem";
            $datos = $con->consultaRetorno($sql);
            return $datos;
        }
        
        public function promedioPorFechas(){                            
            $con = new Conexion();
			$sql = "CREATE OR REPLACE VIEW promedio_fechas AS SELECT `local`.loc_nombre, formulario.for_fecha, formulario.idformulario, categoria.idcategoria, categoria.cat_nombre, item.iditem, item.it_nombre, item.it_descripcion, form_item_resp.idrespuesta, categoria.cat_peso, (SELECT count(item.iditem) FROM item ORDER BY item.iditem) AS items,
			(ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idrespuesta = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien,  
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idrespuesta = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio, 
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idrespuesta = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal, 
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_asplocal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_deposito,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_personal,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_conequipamiento,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_vajilla,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 3 AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pbien_prodinsumos,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 2 AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pintermedio_prodinsumos,
            (ROUND((SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND idrespuesta = 1 AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}')/(SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}'),2))*100 AS pmal_prodinsumos,
			(SELECT COUNT(item.iditem) FROM item) AS total,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 1) AS total_asplocal,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 2) AS total_deposito,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 3) AS total_personal,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 4) AS total_conequipamiento,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 5) AS total_vajilla,
            (SELECT COUNT(item.iditem) FROM item WHERE item.idcategoria = 6) AS total_prodinsumos,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, formulario WHERE form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 1 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_asplocal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 2 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_deposito,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 3 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_personal,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 4 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_conequipamiento,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 5 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_vajilla,
            (SELECT COUNT(form_item_resp.idrespuesta) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = 6 AND form_item_resp.idrespuesta IS NOT NULL AND form_item_resp.idformulario = formulario.idformulario AND formulario.idlocal = {$this->idlocal} AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}') AS evaluados_prodinsumos,
            ((ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 1 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 1 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 1),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 2 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 2 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 2),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 3 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 3 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 3),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 4 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 4 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 4),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 5 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 5 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 5),2),0))+
            (ifnull(ROUND(((SELECT ifnull(SUM(form_item_resp.idrespuesta),0) as suma FROM form_item_resp, item, categoria, formulario WHERE form_item_resp.iditem = item.iditem AND item.idcategoria = categoria.idcategoria AND categoria.idcategoria = 6 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.idlocal = {$this->idlocal})/(SELECT ifnull(COUNT(form_item_resp.idrespuesta),0) FROM form_item_resp, item, formulario WHERE form_item_resp.iditem = item.iditem AND form_item_resp.idrespuesta != 0 AND item.idcategoria = 6 AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND formulario.idlocal = {$this->idlocal}))*(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 6),2),0))) AS promedio_parcial,
            (SELECT ROUND((SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 1)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 2)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 3)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 4)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 5)+(SELECT categoria.cat_peso FROM categoria WHERE categoria.idcategoria = 6),2)) AS suma_pesos

			FROM categoria, item, form_item_resp, formulario, `local`, respuesta WHERE categoria.idcategoria = item.idcategoria AND item.iditem = form_item_resp.iditem AND formulario.idformulario = form_item_resp.idformulario AND formulario.for_fecha <= '{$this->fecha2}' AND formulario.for_fecha >= '{$this->fecha1}' AND `local`.idlocal = formulario.idlocal  AND formulario.idlocal = {$this->idlocal} AND respuesta.idrespuesta = form_item_resp.idrespuesta ORDER BY formulario.idformulario, categoria.idcategoria, item.iditem;";
            $con->consultaSimple($sql);
            $sql1 = "SELECT loc_nombre, idcategoria, cat_nombre, iditem, it_nombre, it_descripcion, SUM(promedio_fechas.idrespuesta) AS suma, cat_peso, (ROUND(CAST(SUM(promedio_fechas.idrespuesta)AS DECIMAL)/COUNT(promedio_fechas.iditem),2)) AS promedio, pbien, pmal, pintermedio, pbien_asplocal, pintermedio_asplocal, pmal_asplocal, pbien_deposito, pintermedio_deposito, pmal_deposito, pbien_personal, pintermedio_personal, pmal_personal, pbien_conequipamiento, pintermedio_conequipamiento, pmal_conequipamiento, pbien_vajilla, pintermedio_vajilla, pmal_vajilla, pbien_prodinsumos, pintermedio_prodinsumos, pmal_prodinsumos, total, total_asplocal, total_deposito, total_personal, total_conequipamiento, total_vajilla, total_prodinsumos, evaluados, evaluados_asplocal, evaluados_deposito, evaluados_personal, evaluados_conequipamiento, evaluados_vajilla, evaluados_prodinsumos, suma_pesos, promedio_parcial, (SELECT COUNT(promedio_fechas.for_fecha)) AS cant_auditorias FROM promedio_fechas GROUP BY promedio_fechas.iditem";
            $datos = $con->consultaRetorno($sql1);
            return $datos;
        }
	}
?>